default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: vending_machine

test: &test
  <<: *default
  database: vending_machine_test
